# Generated by Django 4.1.2 on 2022-11-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_comment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelisting',
            name='imageURL',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Question_mark_%28black%29.svg/800px-Question_mark_%28black%29.svg.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='2022-11-21 18:05:14', max_length=100),
        ),
    ]
