# Generated by Django 4.1.2 on 2022-11-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_comment_datetime_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelisting',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='employee',
            name='imageURL',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Question_mark_%28black%29.svg/800px-Question_mark_%28black%29.svg.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='2022-11-21 20:44:37', max_length=100),
        ),
    ]
