# Generated by Django 4.1.3 on 2022-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_employeelisting_imageurl_employee_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='2022-12-04 17:10:11', max_length=100),
        ),
    ]
