# Generated by Django 4.1.3 on 2022-12-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelisting',
            name='endDay',
        ),
        migrations.RemoveField(
            model_name='employeelisting',
            name='endMonth',
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='2022-12-04 17:45:51', max_length=100),
        ),
    ]
