# Generated by Django 4.1.3 on 2022-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_videosection_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='section',
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='2022-12-21 13:25:44', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecomment',
            name='datetime',
            field=models.CharField(default='2022-12-21 13:25:44', max_length=100),
        ),
        migrations.DeleteModel(
            name='VideoSection',
        ),
    ]
