# Generated by Django 4.1.3 on 2023-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_employeelisting_author_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelisting',
            name='datetime',
            field=models.CharField(default='13:21:57 01-27-2023', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='2023-01-27 13:21:57', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecomment',
            name='datetime',
            field=models.CharField(default='2023-01-27 13:21:57', max_length=100),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='datetime',
            field=models.CharField(default='13:21:57 01-27-2023', max_length=100),
        ),
    ]
