# Generated by Django 4.1.3 on 2023-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0056_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='2023-01-27 14:18:21', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecomment',
            name='datetime',
            field=models.CharField(default='2023-01-27 14:18:21', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeelisting',
            name='datetime',
            field=models.CharField(default='14:18:21 EST, 01-27-2023', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='supply', max_length=1000),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='datetime',
            field=models.CharField(default='14:18:21 01-27-2023', max_length=100),
        ),
    ]
