# Generated by Django 4.1.3 on 2023-02-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0060_dog_rooms_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default='02-25-2023 11:08:10', max_length=100),
        ),
        migrations.AlterField(
            model_name='doglisting',
            name='datetime',
            field=models.CharField(default='11:08:10 02-25-2023', max_length=100),
        ),
        migrations.AlterField(
            model_name='doglisting',
            name='dog',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.dog'),
        ),
        migrations.AlterField(
            model_name='employeecomment',
            name='datetime',
            field=models.CharField(default='02-25-2023 11:08:10', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeelisting',
            name='datetime',
            field=models.CharField(default='11:08:10 EST, 02-25-2023', max_length=100),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='datetime',
            field=models.CharField(default='11:08:10 02-25-2023', max_length=100),
        ),
    ]
